# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushDeer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 15.0'
  pod "PromiseKit", "~> 6.8"

  # Pods for PushDeer

end

target 'PushDeerClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 15.0'
  pod "PromiseKit", "~> 6.8"

  # Pods for PushDeer

end


